### ISSUE TITLE
Color of the answers once selected.

### ISSUE THREAD

**Issue by Aidyl98** [Root-101/citmatel_strawberry_trivia#16]
- [ ] When the user answers correctly, the correct answer is shown in green. Others in normal Color
- [ ] When the answer is wrong, the user's selection is shown in red and the correct answer in green.
- [ ] The other options remain in the color they had or are grayed out as to downplay it, for consideration.

**Comment by JesusHdezWaterloo** [comment]
Por que esto no se ha cerrado?

**Comment by Aidyl98** [comment]
No se ha cerrado porque no se ha resuelto el problema. Las opciones que no fueron la correcta o la incorrecta por el usuario se siguen coloreando de rojo.
