### ISSUE TITLE
Dots

### ISSUE THREAD

**Issue by JesusHdezWaterloo** [Root-101/citmatel_strawberry_trivia#26]
- [x] Muchos dots se salen de la pantalla
- [x] poner en cada dots si se completó bien o mal con color e icono

**Comment by Aidyl98** [comment]
The `IconStepper` from the [im_stepper](https://pub.dev/packages/im_stepper) package was used to put the tright or wrong icon in each one of the questions dots. The color of each one was not used because estiticly was better with out them.
