### ISSUE TITLE
Terminar nivel vuelva a pantalla de niveles

### ISSUE THREAD

**Issue by JesusHdezWaterloo** [Root-101/citmatel_strawberry_trivia#6]
Al terminar un subnivel que salga un cartel de notificación y se regrese a la pagina con todos los subniveles

- [x] home on win
- [x] home on loose
- [x] next on win
- [x] reset on loose

**Comment by JesusHdezWaterloo** [comment]
si esto es lo de pasar a la ventana de win-loose xq no se ha cerrado el issue si ya se hizo

**Comment by Aidyl98** [comment]
Lo que se implementó fueron las pantallas de ganar o perder. Hay que desarrollar que cuando se pulse sobre un botón se regrese a la pantalla de niveles, se reinicie el nivel o se avance hacia el siguiente.
