### ISSUE TITLE
Logica general de la trivia

### ISSUE THREAD

**Issue by JesusHdezWaterloo** [Root-101/citmatel_strawberry_trivia#8]
Ver finalmente como se va a hacer la trivia
- [X] si un temporizador por pregunta o uno general
- [x] que pasa cuando se completa una pregunta, si se muestra una pista, o espera los 3 seg como está
- [X] el click en el dot cambia el nivel sin completarlo

**Comment by Aidyl98** [comment]
The line _onDotTapped:_ whas commented so the dot dosen't change if the user toch it.

**Comment by Aidyl98** [comment]
When the user reach out of time he lose, so it calls Strawberry Function.looseLevel();

**Comment by JesusHdezWaterloo** [comment]
Un temporizador por pregunta
